# Generated by Django 2.2.19 on 2021-06-16 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('safe_driver', '0052_pretripcargoareabus_pretripinterioroperationbus_pretriprampbus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('question_type', models.CharField(choices=[('multiple', 'Multiple'), ('single', 'Single')], default='single', max_length=20, verbose_name='Question Type')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='StudentTestExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='studenttest_exam', to='csd_quizes.Exam')),
                ('test', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exam_studenttest', to='safe_driver.StudentTest')),
            ],
            options={
                'verbose_name': 'Student Test Exam',
                'verbose_name_plural': 'Student Test Exams',
                'ordering': ('created',),
                'unique_together': {('test', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='choice_question', to='csd_quizes.Question')),
            ],
            options={
                'verbose_name': 'Question Choice',
                'verbose_name_plural': 'Question Choices',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('answers', models.ManyToManyField(to='csd_quizes.QuestionChoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='csd_quizes.Question')),
                ('test_exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answer_student_test_exam', to='csd_quizes.StudentTestExam')),
            ],
            options={
                'verbose_name': 'Question Answer',
                'verbose_name_plural': 'Question Answers',
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='question_choices', to='csd_quizes.QuestionChoice'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_choices',
            field=models.ManyToManyField(blank=True, related_name='question_answer_choices', to='csd_quizes.QuestionChoice'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='csd_quizes.Exam'),
        ),
    ]
