# Generated by Django 2.2.19 on 2021-06-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd_quizes', '0002_auto_20210616_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionchoice',
            options={'ordering': ('position',), 'verbose_name': 'Question Choice', 'verbose_name_plural': 'Question Choices'},
        ),
        migrations.AddConstraint(
            model_name='questionanswer',
            constraint=models.UniqueConstraint(fields=('test_exam', 'question'), name='answer_test_exam_question_unique_contraint'),
        ),
    ]
