# Generated by Django 2.2.24 on 2021-09-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csd_quizes', '0003_auto_20210617_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('defensive_driving', 'Defensive Driving Quiz'), ('distracted', 'Distracted Quiz')], default=None, max_length=32, null=True, verbose_name='Exam Type'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(exam_type__isnull=False), fields=('exam_type',), name='unique_exam_type'),
        ),
    ]
