# Generated by Django 2.2.24 on 2021-10-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csd_quizes', '0004_auto_20210923_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('position',), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
