# Generated by Django 2.2.24 on 2021-10-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csd_quizes', '0006_auto_20211007_0239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ('question__position', 'answers__position'), 'verbose_name': 'Question Answer', 'verbose_name_plural': 'Question Answers'},
        ),
    ]
