# Generated by Django 2.2.24 on 2021-12-06 11:12

from django.db import migrations, models
import safe_driver.image_functions


class Migration(migrations.Migration):

    dependencies = [
        ('csd_quizes', '0007_auto_20211007_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttestexam',
            name='company_rep_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Company Rep. Name'),
        ),
        migrations.AddField(
            model_name='studenttestexam',
            name='company_rep_signature',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=safe_driver.image_functions.signature_image_folder_exam, verbose_name='Company Rep Signature'),
        ),
        migrations.AddField(
            model_name='studenttestexam',
            name='driver_signature',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=safe_driver.image_functions.signature_image_folder_exam, verbose_name='Driver Signature'),
        ),
        migrations.AddField(
            model_name='studenttestexam',
            name='evaluator_signature',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=safe_driver.image_functions.signature_image_folder_exam, verbose_name='Evaluator Signature'),
        ),
    ]
