export const INSTRUCTOR = {
  GET_INSTRUCTOR: 'GET_INSTRUCTOR',
  GET_INSTRUCTOR_SUCCESS: 'GET_INSTRUCTOR_SUCCESS',
  GET_INSTRUCTOR_ERROR: 'GET_INSTRUCTOR_ERROR',

  UPDATE_INSTRUCTOR: 'UPDATE_INSTRUCTOR',
  UPDATE_INSTRUCTOR_SUCCESS: 'UPDATE_INSTRUCTOR_SUCCESS',
  UPDATE_INSTRUCTOR_ERROR: 'UPDATE_INSTRUCTOR_ERROR',

  ADD_INSTRUCTOR: 'ADD_INSTRUCTOR',
  ADD_INSTRUCTOR_SUCCESS: 'ADD_INSTRUCTOR_SUCCESS',
  ADD_INSTRUCTOR_ERROR: 'ADD_INSTRUCTOR_ERROR',
};

const getInstructor = () => ({
  type: INSTRUCTOR.GET_INSTRUCTOR,
});

const updateInstructor = payload => ({
  type: INSTRUCTOR.UPDATE_INSTRUCTOR,
  payload,
});

const addInstructor = payload => ({
  type: INSTRUCTOR.ADD_INSTRUCTOR,
  payload,
});

export { getInstructor, updateInstructor, addInstructor };
