# Generated by Django 2.2.17 on 2021-02-10 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safe_driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_company', to='safe_driver.Company'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safedriveswp',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swp_student_test', to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='safedriveprod',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prod_student_test', to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='safedrivepretrip',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safedrivepretrip',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='safedrivenote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safedrivenote',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='safedriveeye',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eye_student_test', to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='safedriveequipment',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equip_student_test', to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='safedrivebtw',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safedrivebtw',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='pretripvehiclerearclassc',
            name='pre_trip_class_c',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_vehicle_rear_class_c', to='safe_driver.PreTripClassC'),
        ),
        migrations.AddField(
            model_name='pretripvehicleortractorrearclassd',
            name='pre_trip_class_d',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_vehicle_or_tractor_rear_class_d', to='safe_driver.PreTripClassD'),
        ),
        migrations.AddField(
            model_name='pretripvehicleortractorrearclassb',
            name='pre_trip_class_b',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_vehicle_or_tractor_rear_class_b', to='safe_driver.PreTripClassB'),
        ),
        migrations.AddField(
            model_name='pretripvehicleortractorrearclassa',
            name='pre_trip_class_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_vehicle_or_tractor_rear_class_a', to='safe_driver.PreTripClassA'),
        ),
        migrations.AddField(
            model_name='pretripvehicleortractorrear',
            name='pre_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDrivePreTrip'),
        ),
        migrations.AddField(
            model_name='pretripvehiclefrontclassd',
            name='pre_trip_class_d',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_vehicle_front_class_d', to='safe_driver.PreTripClassD'),
        ),
        migrations.AddField(
            model_name='pretripvehiclefrontclassc',
            name='pre_trip_class_c',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_vehicle_front_class_c', to='safe_driver.PreTripClassC'),
        ),
        migrations.AddField(
            model_name='pretripvehiclefrontclassb',
            name='pre_trip_class_b',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_vehicle_front_class_b', to='safe_driver.PreTripClassB'),
        ),
        migrations.AddField(
            model_name='pretripvehiclefrontclassa',
            name='pre_trip_class_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_vehicle_front_class_a', to='safe_driver.PreTripClassA'),
        ),
        migrations.AddField(
            model_name='pretripvehiclefront',
            name='pre_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDrivePreTrip'),
        ),
        migrations.AddField(
            model_name='pretripreartrailerboxclassd',
            name='pre_trip_class_d',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_rear_trailer_box_class_d', to='safe_driver.PreTripClassD'),
        ),
        migrations.AddField(
            model_name='pretripreartrailerboxclassa',
            name='pre_trip_class_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_rear_trailer_box_class_a', to='safe_driver.PreTripClassA'),
        ),
        migrations.AddField(
            model_name='pretripreartrailerbox',
            name='pre_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDrivePreTrip'),
        ),
        migrations.AddField(
            model_name='pretripposttripclassd',
            name='pre_trip_class_d',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_posttrip_class_d', to='safe_driver.PreTripClassD'),
        ),
        migrations.AddField(
            model_name='pretripposttripclassc',
            name='pre_trip_class_c',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_posttrip_class_c', to='safe_driver.PreTripClassC'),
        ),
        migrations.AddField(
            model_name='pretripposttripclassb',
            name='pre_trip_class_b',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_posttrip_class_b', to='safe_driver.PreTripClassB'),
        ),
        migrations.AddField(
            model_name='pretripposttripclassa',
            name='pre_trip_class_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_posttrip_class_a', to='safe_driver.PreTripClassA'),
        ),
        migrations.AddField(
            model_name='pretripposttrip',
            name='pre_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDrivePreTrip'),
        ),
        migrations.AddField(
            model_name='pretrippassengersidetrailerboxclassd',
            name='pre_trip_class_d',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_passenger_side_trailer_box_class_d', to='safe_driver.PreTripClassD'),
        ),
        migrations.AddField(
            model_name='pretrippassengersidetrailerboxclassa',
            name='pre_trip_class_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_passenger_side_trailer_box_class_a', to='safe_driver.PreTripClassA'),
        ),
        migrations.AddField(
            model_name='pretrippassengersidetrailerbox',
            name='pre_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDrivePreTrip'),
        ),
        migrations.AddField(
            model_name='pretrippassengersideboxclassb',
            name='pre_trip_class_b',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_passenger_side_box_class_b', to='safe_driver.PreTripClassB'),
        ),
        migrations.AddField(
            model_name='pretripinsidecabclassd',
            name='pre_trip_class_d',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_insidecab_class_d', to='safe_driver.PreTripClassD'),
        ),
        migrations.AddField(
            model_name='pretripinsidecabclassc',
            name='pre_trip_class_c',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_insidecab_class_c', to='safe_driver.PreTripClassC'),
        ),
        migrations.AddField(
            model_name='pretripinsidecabclassb',
            name='pre_trip_class_b',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_insidecab_class_b', to='safe_driver.PreTripClassB'),
        ),
        migrations.AddField(
            model_name='pretripinsidecabclassa',
            name='pre_trip_class_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_insidecab_class_a', to='safe_driver.PreTripClassA'),
        ),
        migrations.AddField(
            model_name='pretripinsidecab',
            name='pre_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDrivePreTrip'),
        ),
        migrations.AddField(
            model_name='pretripfronttrailerboxclassd',
            name='pre_trip_class_d',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_front_trailer_box_class_d', to='safe_driver.PreTripClassD'),
        ),
        migrations.AddField(
            model_name='pretripfronttrailerboxclassa',
            name='pre_trip_class_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_front_trailer_box_class_a', to='safe_driver.PreTripClassA'),
        ),
        migrations.AddField(
            model_name='pretripfronttrailerbox',
            name='pre_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDrivePreTrip'),
        ),
        migrations.AddField(
            model_name='pretripenginecompartmentclassd',
            name='pre_trip_class_d',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_engine_compartment_class_d', to='safe_driver.PreTripClassD'),
        ),
        migrations.AddField(
            model_name='pretripenginecompartmentclassc',
            name='pre_trip_class_c',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_engine_compartment_class_c', to='safe_driver.PreTripClassC'),
        ),
        migrations.AddField(
            model_name='pretripenginecompartmentclassb',
            name='pre_trip_class_b',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_engine_compartment_class_b', to='safe_driver.PreTripClassB'),
        ),
        migrations.AddField(
            model_name='pretripenginecompartmentclassa',
            name='pre_trip_class_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_engine_compartment_class_a', to='safe_driver.PreTripClassA'),
        ),
        migrations.AddField(
            model_name='pretripenginecompartment',
            name='pre_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDrivePreTrip'),
        ),
        migrations.AddField(
            model_name='pretripdriversidetrailerboxclassd',
            name='pre_trip_class_d',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_driver_side_trailer_box_class_d', to='safe_driver.PreTripClassD'),
        ),
        migrations.AddField(
            model_name='pretripdriversidetrailerboxclassa',
            name='pre_trip_class_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_driver_side_trailer_box_class_a', to='safe_driver.PreTripClassA'),
        ),
        migrations.AddField(
            model_name='pretripdriversidetrailerbox',
            name='pre_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDrivePreTrip'),
        ),
        migrations.AddField(
            model_name='pretripdriversideboxclassb',
            name='pre_trip_class_b',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_driver_side_box_class_b', to='safe_driver.PreTripClassB'),
        ),
        migrations.AddField(
            model_name='pretripdollyclassd',
            name='pre_trip_class_d',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_dolly_class_d', to='safe_driver.PreTripClassD'),
        ),
        migrations.AddField(
            model_name='pretripdollyclassa',
            name='pre_trip_class_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_dolly_class_a', to='safe_driver.PreTripClassA'),
        ),
        migrations.AddField(
            model_name='pretripdolly',
            name='pre_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDrivePreTrip'),
        ),
        migrations.AddField(
            model_name='pretripcombinationvehicles',
            name='pre_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDrivePreTrip'),
        ),
        migrations.AddField(
            model_name='pretripcoalsclassd',
            name='pre_trip_class_d',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_coals_class_d', to='safe_driver.PreTripClassD'),
        ),
        migrations.AddField(
            model_name='pretripcoalsclassb',
            name='pre_trip_class_b',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_coals_class_b', to='safe_driver.PreTripClassB'),
        ),
        migrations.AddField(
            model_name='pretripcoalsclassa',
            name='pre_trip_class_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_coals_class_a', to='safe_driver.PreTripClassA'),
        ),
        migrations.AddField(
            model_name='pretripcoals',
            name='pre_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDrivePreTrip'),
        ),
        migrations.AddField(
            model_name='pretripclassd',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_student_test_class_d', to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='pretripclassc',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_student_test_class_c', to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='pretripclassb',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_student_test_class_b', to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='pretripclassa',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_student_test_class_a', to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='pretripcargoareaclassc',
            name='pre_trip_class_c',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_cargo_area_class_c', to='safe_driver.PreTripClassC'),
        ),
        migrations.AddField(
            model_name='pretripcargoareaclassb',
            name='pre_trip_class_b',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_cargo_area_class_b', to='safe_driver.PreTripClassB'),
        ),
        migrations.AddField(
            model_name='pretripboxheaderboardclassb',
            name='pre_trip_class_b',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_box_header_board_class_b', to='safe_driver.PreTripClassB'),
        ),
        migrations.AddField(
            model_name='pretripbothsidesvehiclesclassd',
            name='pre_trip_class_d',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_both_sides_vehicle_class_d', to='safe_driver.PreTripClassD'),
        ),
        migrations.AddField(
            model_name='pretripbothsidesvehiclesclassc',
            name='pre_trip_class_c',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_both_sides_vehicle_class_c', to='safe_driver.PreTripClassC'),
        ),
        migrations.AddField(
            model_name='pretripbothsidesvehiclesclassb',
            name='pre_trip_class_b',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_both_sides_vehicle_class_b', to='safe_driver.PreTripClassB'),
        ),
        migrations.AddField(
            model_name='pretripbothsidesvehiclesclassa',
            name='pre_trip_class_a',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_both_sides_vehicle_class_a', to='safe_driver.PreTripClassA'),
        ),
        migrations.AddField(
            model_name='pretripbothsidesvehicle',
            name='pre_trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDrivePreTrip'),
        ),
        migrations.AddField(
            model_name='pasturning',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='passteering',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='passtartengine',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='passpeed',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='passengervehicles',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_vehicle_test', to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='pasrecognizeshazards',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='pasrailroadcrossing',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='paspassing',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='paspassengersafety',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='pasparking',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='paslightsandsignals',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='pasintersections',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='pashills',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='pasgeneralsafetyanddotadherence',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='paseyemovementandmirror',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='pasengineoperation',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='pascabsafety',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='pasbrakesandstoppings',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='pasbacking',
            name='pas',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.PassengerVehicles'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_company', to='safe_driver.Company'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='btwuncouplingclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_uncoupling_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwuncouplingclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_uncoupling_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwuncoupling',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwturningclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_turning_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwturningclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_turning_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwturningclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_turning_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwturningclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_turning_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwturning',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwsteeringclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_steering_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwsteeringclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_steering_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwsteeringclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_steering_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwsteeringclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_steering_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwsteering',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwstartengineclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_start_engine_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwstartengineclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_start_engine_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwstartengineclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_start_engine_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwstartengineclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_start_engine_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwstartengine',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwspeedclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_speed_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwspeedclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_speed_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwspeedclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_speed_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwspeedclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_speed_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwspeed',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwrecognizeshazardsclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_recognizes_hazards_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwrecognizeshazardsclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_recognizes_hazards_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwrecognizeshazardsclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_recognizes_hazards_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwrecognizeshazardsclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_recognizes_hazards_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwrecognizeshazards',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwpassingclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_passing_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwpassingclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_passing_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwpassingclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_passing_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwpassingclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_passing_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwpassing',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwparkingclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_parking_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwparkingclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_parking_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwparkingclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_parking_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwparkingclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_parking_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwparking',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwmultipletrailersclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_multiple_trailers_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwmultipletrailersclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_multiple_trailers_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwmultipletrailers',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwlightsandsignalsclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_lights_and_signals_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwlightsandsignalsclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_lights_and_signals_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwlightsandsignalsclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_lights_and_signals_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwlightsandsignalsclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_lights_and_signals_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwlightsandsignals',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwintersectionsclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_intersections_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwintersectionsclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_intersections_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwintersectionsclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_intersections_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwintersectionsclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_intersections_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwintersections',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwhillsclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_hills_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwhillsclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_hills_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwhillsclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_hills_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwhillsclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_hills_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwhills',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwgeneralsafetyanddotadherenceclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_general_safety_and_dot_adherence_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwgeneralsafetyanddotadherenceclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_general_safety_and_dot_adherence_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwgeneralsafetyanddotadherenceclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_general_safety_and_dot_adherence_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwgeneralsafetyanddotadherenceclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_general_safety_and_dot_adherence_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwgeneralsafetyanddotadherence',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btweyemovementandmirrorclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_eye_movement_and_mirror_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btweyemovementandmirrorclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_eye_movement_and_mirror_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btweyemovementandmirrorclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_eye_movement_and_mirror_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btweyemovementandmirrorclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_eye_movement_and_mirror_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btweyemovementandmirror',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwengineoperationclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_engine_operation_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwengineoperationclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_engine_operation_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwengineoperationclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_engine_operation_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwengineoperationclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_engine_operation_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwengineoperation',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwcouplingclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_coupling_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwcouplingclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_coupling_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwcoupling',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwclutchandtransmissionclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_clutch_and_transmission_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwclutchandtransmissionclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_clutch_and_transmission_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwclutchandtransmissionclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_clutch_and_transmission_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwclutchandtransmissionclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_clutch_and_transmission_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwclutchandtransmission',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwclassd',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btw_test_class_d', to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='btwclassc',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btw_test_class_c', to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='btwclassb',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btw_test_class_b', to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='btwclassa',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btw_test_class_a', to='safe_driver.StudentTest'),
        ),
        migrations.AddField(
            model_name='btwcabsafetyclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_cab_safety_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwcabsafetyclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_cab_safety_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwcabsafetyclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_cab_safety_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwcabsafetyclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_cab_safety_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwcabsafety',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwbrakesandstoppingsclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_brakes_and_stopping_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwbrakesandstoppingsclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_brakes_and_stoppings_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwbrakesandstoppingsclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_brakes_and_stoppings_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwbrakesandstoppingsclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_brakes_and_stopping_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwbrakesandstoppings',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
        migrations.AddField(
            model_name='btwbackingclassd',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_backing_class_d', to='safe_driver.BTWClassD'),
        ),
        migrations.AddField(
            model_name='btwbackingclassc',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_backing_class_c', to='safe_driver.BTWClassC'),
        ),
        migrations.AddField(
            model_name='btwbackingclassb',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_backing_class_b', to='safe_driver.BTWClassB'),
        ),
        migrations.AddField(
            model_name='btwbackingclassa',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='btw_backing_class_a', to='safe_driver.BTWClassA'),
        ),
        migrations.AddField(
            model_name='btwbacking',
            name='btw',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveBTW'),
        ),
    ]
