# Generated by Django 2.2.17 on 2021-02-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0003_studenttestinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_test', to='safe_driver.StudentTest')),
            ],
            options={
                'verbose_name': 'Test Note',
                'verbose_name_plural': 'Test Notes',
                'ordering': ('test__student__first_name', 'test__student__last_name', '-created'),
            },
        ),
    ]
