# Generated by Django 2.2.17 on 2021-02-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0004_studenttestnotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentTestNotes',
            new_name='StudentTestNote',
        ),
    ]
