# Generated by Django 2.2.17 on 2021-02-16 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0006_safedriveeye_eye_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_unit_number', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Power Unit Number')),
                ('transmission_type', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Permission Type')),
                ('vehicle_type', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Vehicle Type')),
                ('vehicle_type_other', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Vehicle Type Other')),
                ('vehicle_manufacturer', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Vehicle Manufacturer')),
                ('vehicle_manufacturer_other', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Vehicle Manufacturer Other')),
                ('single_trailer_length', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Single Trailer Length')),
                ('single_trailer_length_other', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Single Trailer Length Other')),
                ('combination_vehicles', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Combination Vehicles')),
                ('combinations_vehicles_other', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Combination Vehicles Other')),
                ('combination_vehicles_length', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Combination Vehicles Other')),
                ('combination_vehicles_length_other', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Combination Vehicles Length Other')),
                ('dolly_or_gear_type', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Dolly/Gear Type')),
                ('dolly_or_gear_type_other', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Dolly/Gear Type Other')),
                ('trailer_1', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('trailer_2', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('trailer_3', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('dolly_1', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('dolly_2', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equip_student_test', to='safe_driver.StudentTest')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProdItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Location')),
                ('trailer', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Trailer')),
                ('start_work', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, null=True, verbose_name='Start Work')),
                ('leave_building', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Leave Building')),
                ('travel_path', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Travel Path')),
                ('speed', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Speed')),
                ('idle_time', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Idle Time')),
                ('plan_ahead', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Plan Ahead')),
                ('turn_around', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Turn Around')),
                ('on_schedule', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='On Schedule')),
                ('customer_contact', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Customer Contact')),
                ('not_ready_situations', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Not Ready Situations')),
                ('brisk_pace', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Brisk Pace')),
                ('finish_work', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Finish Work')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prod Item',
                'verbose_name_plural': 'Prod Items',
            },
        ),
        migrations.RemoveField(
            model_name='safedriveprod',
            name='brisk_pace',
        ),
        migrations.RemoveField(
            model_name='safedriveprod',
            name='customer_contact',
        ),
        migrations.RemoveField(
            model_name='safedriveprod',
            name='finish_work',
        ),
        migrations.RemoveField(
            model_name='safedriveprod',
            name='idle_time',
        ),
        migrations.RemoveField(
            model_name='safedriveprod',
            name='leave_building',
        ),
        migrations.RemoveField(
            model_name='safedriveprod',
            name='location',
        ),
        migrations.RemoveField(
            model_name='safedriveprod',
            name='not_ready_situations',
        ),
        migrations.RemoveField(
            model_name='safedriveprod',
            name='on_schedule',
        ),
        migrations.RemoveField(
            model_name='safedriveprod',
            name='plan_ahead',
        ),
        migrations.RemoveField(
            model_name='safedriveprod',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='safedriveprod',
            name='start_work',
        ),
        migrations.RemoveField(
            model_name='safedriveprod',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='safedriveprod',
            name='travel_path',
        ),
        migrations.RemoveField(
            model_name='safedriveprod',
            name='turn_around',
        ),
        migrations.DeleteModel(
            name='SafeDriveEquipment',
        ),
        migrations.AddField(
            model_name='proditem',
            name='equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.SafeDriveProd'),
        ),
    ]
