# Generated by Django 2.2.17 on 2021-02-16 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0007_auto_20210217_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proditem',
            old_name='equip',
            new_name='prod',
        ),
    ]
