# Generated by Django 2.2.17 on 2021-03-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0009_auto_20210217_1656'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
