# Generated by Django 2.2.17 on 2021-03-04 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0011_studentgroup_studentinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='user',
            new_name='student',
        ),
    ]
