# Generated by Django 2.2.17 on 2021-03-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0012_auto_20210305_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttestinfo',
            name='corrective_lense_required',
        ),
        migrations.RemoveField(
            model_name='studenttestinfo',
            name='dot_expiration_date',
        ),
        migrations.RemoveField(
            model_name='studenttestinfo',
            name='driver_duty_status',
        ),
        migrations.RemoveField(
            model_name='studenttestinfo',
            name='driver_eld_exempt',
        ),
        migrations.RemoveField(
            model_name='studenttestinfo',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='studenttestinfo',
            name='driver_license_class',
        ),
        migrations.RemoveField(
            model_name='studenttestinfo',
            name='driver_license_expire_date',
        ),
        migrations.RemoveField(
            model_name='studenttestinfo',
            name='driver_license_number',
        ),
        migrations.RemoveField(
            model_name='studenttestinfo',
            name='driver_license_state',
        ),
        migrations.RemoveField(
            model_name='studenttestinfo',
            name='endorsements',
        ),
        migrations.RemoveField(
            model_name='studenttestinfo',
            name='location',
        ),
    ]
