# Generated by Django 2.2.19 on 2021-03-06 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0013_auto_20210305_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_company', to='safe_driver.Company'),
        ),
    ]
