# Generated by Django 2.2.19 on 2021-03-06 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0014_studentinfo_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttestinfo',
            name='company',
        ),
    ]
