# Generated by Django 2.2.19 on 2021-03-06 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0015_remove_studenttestinfo_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentinfo',
            options={'ordering': ('student__username',), 'verbose_name': 'Student Info', 'verbose_name_plural': 'Students Info'},
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='safe_driver.StudentGroup'),
        ),
    ]
