# Generated by Django 2.2.19 on 2021-03-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0016_auto_20210306_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'ordering': ('name',), 'verbose_name': 'Student Group', 'verbose_name_plural': 'Student Groups'},
        ),
        migrations.RenameField(
            model_name='pretripenginecompartmentclassb',
            old_name='tire_and_rin_condition',
            new_name='tire_and_rim_condition',
        ),
    ]
