# Generated by Django 2.2.19 on 2021-03-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0017_auto_20210311_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pretripenginecompartmentclassc',
            old_name='tire_and_rin_condition',
            new_name='tire_and_rim_condition',
        ),
    ]
