# Generated by Django 2.2.19 on 2021-03-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0022_auto_20210321_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionBTWBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('field_name', models.CharField(default=None, help_text='Type/select field name underscore and without any space matched with db field', max_length=32, unique=True, verbose_name='Field Name')),
            ],
            options={
                'verbose_name': 'Instruction for BTW BUS',
                'verbose_name_plural': 'Instructions for BTW BUS',
                'ordering': ('field_name',),
            },
        ),
        migrations.CreateModel(
            name='InstructionBTWClassA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('field_name', models.CharField(default=None, help_text='Type/select field name underscore and without any space matched with db field', max_length=32, unique=True, verbose_name='Field Name')),
            ],
            options={
                'verbose_name': 'Instruction for BTW Class A',
                'verbose_name_plural': 'Instructions for BTW Class A',
                'ordering': ('field_name',),
            },
        ),
        migrations.CreateModel(
            name='InstructionBTWClassB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('field_name', models.CharField(default=None, help_text='Type/select field name underscore and without any space matched with db field', max_length=32, unique=True, verbose_name='Field Name')),
            ],
            options={
                'verbose_name': 'Instruction for BTW Class B',
                'verbose_name_plural': 'Instructions for BTW Class B',
                'ordering': ('field_name',),
            },
        ),
        migrations.CreateModel(
            name='InstructionBTWClassC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('field_name', models.CharField(default=None, help_text='Type/select field name underscore and without any space matched with db field', max_length=32, unique=True, verbose_name='Field Name')),
            ],
            options={
                'verbose_name': 'Instruction for BTW Class C',
                'verbose_name_plural': 'Instructions for BTW Class C',
                'ordering': ('field_name',),
            },
        ),
    ]
