# Generated by Django 2.2.19 on 2021-04-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0023_instructionbtwbus_instructionbtwclassa_instructionbtwclassb_instructionbtwclassc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentprobabilityvaluebtwbus',
            name='value',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Postive Value', max_digits=4, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='accidentprobabilityvaluebtwclassa',
            name='value',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Postive Value', max_digits=4, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='accidentprobabilityvaluebtwclassb',
            name='value',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Postive Value', max_digits=4, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='accidentprobabilityvaluebtwclassc',
            name='value',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Postive Value', max_digits=4, verbose_name='Value'),
        ),
    ]
