# Generated by Django 2.2.19 on 2021-04-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0024_auto_20210401_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentProbabilityValuePreTripClassC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Name')),
                ('key', models.CharField(choices=[('animal', 'Animal'), ('backing', 'Backing'), ('cyclist', 'Cyclist'), ('entering_exiting', 'Entering/Exiting'), ('hazardous_materials', 'Hazardous Materials'), ('head_on_collision', 'Head-on Collision'), ('hit_in_rear', 'Hit in Rear'), ('hit_other_in_rear', 'Hit Other in Rear'), ('hit_parked_vehicle', 'Hit Parked Vehicle'), ('hit_stationary_object', 'Hit Stationary Object'), ('hit_while_parked', 'Hit While Parked'), ('intersection', 'Intersection'), ('jacknife', 'Jacknife'), ('moving_object', 'Moving Object'), ('parking_lot', 'Parking Lot'), ('rollaway', 'Rollaway'), ('sideswipe', 'Sideswipe')], default=None, help_text='Type key name underscore and without any space', max_length=32, verbose_name='Key')),
                ('field_name', models.CharField(default=None, help_text='Type field name underscore and without any space matched with db field', max_length=32, verbose_name='Field')),
                ('value', models.DecimalField(decimal_places=2, default=None, help_text='Postive Value', max_digits=4, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Accident Probability Value PreTrip Class C',
                'verbose_name_plural': 'Accident Probability Value PreTrip Class C',
                'ordering': ('key', 'field_name'),
                'unique_together': {('key', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='AccidentProbabilityValuePreTripClassB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Name')),
                ('key', models.CharField(choices=[('animal', 'Animal'), ('backing', 'Backing'), ('cyclist', 'Cyclist'), ('entering_exiting', 'Entering/Exiting'), ('hazardous_materials', 'Hazardous Materials'), ('head_on_collision', 'Head-on Collision'), ('hit_in_rear', 'Hit in Rear'), ('hit_other_in_rear', 'Hit Other in Rear'), ('hit_parked_vehicle', 'Hit Parked Vehicle'), ('hit_stationary_object', 'Hit Stationary Object'), ('hit_while_parked', 'Hit While Parked'), ('intersection', 'Intersection'), ('jacknife', 'Jacknife'), ('moving_object', 'Moving Object'), ('parking_lot', 'Parking Lot'), ('rollaway', 'Rollaway'), ('sideswipe', 'Sideswipe')], default=None, help_text='Type key name underscore and without any space', max_length=32, verbose_name='Key')),
                ('field_name', models.CharField(default=None, help_text='Type field name underscore and without any space matched with db field', max_length=32, verbose_name='Field')),
                ('value', models.DecimalField(decimal_places=2, default=None, help_text='Postive Value', max_digits=4, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Accident Probability Value BTW Class B',
                'verbose_name_plural': 'Accident Probability Value BTW Class B',
                'ordering': ('key', 'field_name'),
                'unique_together': {('key', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='AccidentProbabilityValuePreTripClassA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Name')),
                ('key', models.CharField(choices=[('animal', 'Animal'), ('backing', 'Backing'), ('cyclist', 'Cyclist'), ('entering_exiting', 'Entering/Exiting'), ('hazardous_materials', 'Hazardous Materials'), ('head_on_collision', 'Head-on Collision'), ('hit_in_rear', 'Hit in Rear'), ('hit_other_in_rear', 'Hit Other in Rear'), ('hit_parked_vehicle', 'Hit Parked Vehicle'), ('hit_stationary_object', 'Hit Stationary Object'), ('hit_while_parked', 'Hit While Parked'), ('intersection', 'Intersection'), ('jacknife', 'Jacknife'), ('moving_object', 'Moving Object'), ('parking_lot', 'Parking Lot'), ('rollaway', 'Rollaway'), ('sideswipe', 'Sideswipe')], default=None, help_text='Type key name underscore and without any space', max_length=32, verbose_name='Key')),
                ('field_name', models.CharField(default=None, help_text='Type field name underscore and without any space matched with db field', max_length=32, verbose_name='Field Name')),
                ('value', models.DecimalField(decimal_places=2, default=None, help_text='Postive Value', max_digits=4, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Accident Probability Value PreTrip Class A',
                'verbose_name_plural': 'Accident Probability Value PreTrip Class A',
                'ordering': ('key', 'field_name'),
                'unique_together': {('key', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='AccidentProbabilityValuePreTripBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Name')),
                ('key', models.CharField(choices=[('animal', 'Animal'), ('backing', 'Backing'), ('cyclist', 'Cyclist'), ('entering_exiting', 'Entering/Exiting'), ('hazardous_materials', 'Hazardous Materials'), ('head_on_collision', 'Head-on Collision'), ('hit_in_rear', 'Hit in Rear'), ('hit_other_in_rear', 'Hit Other in Rear'), ('hit_parked_vehicle', 'Hit Parked Vehicle'), ('hit_stationary_object', 'Hit Stationary Object'), ('hit_while_parked', 'Hit While Parked'), ('intersection', 'Intersection'), ('jacknife', 'Jacknife'), ('moving_object', 'Moving Object'), ('parking_lot', 'Parking Lot'), ('rollaway', 'Rollaway'), ('sideswipe', 'Sideswipe')], default=None, help_text='Type key name underscore and without any space', max_length=32, verbose_name='Key')),
                ('field_name', models.CharField(default=None, help_text='Type field name underscore and without any space matched with db field', max_length=32, verbose_name='Field')),
                ('value', models.DecimalField(decimal_places=2, default=None, help_text='Postive Value', max_digits=4, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Accident Probability Value PreTrip BUS',
                'verbose_name_plural': 'Accident Probability Value PreTrip BUS',
                'ordering': ('key', 'field_name'),
                'unique_together': {('key', 'field_name')},
            },
        ),
    ]
