# Generated by Django 2.2.19 on 2021-04-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0025_accidentprobabilityvaluepretripbus_accidentprobabilityvaluepretripclassa_accidentprobabilityvaluepre'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionPreTripBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('field_name', models.CharField(default=None, help_text='Type/select field name underscore and without any space matched with db field', max_length=32, unique=True, verbose_name='Field Name')),
            ],
            options={
                'verbose_name': 'Instruction for PreTrip BUS',
                'verbose_name_plural': 'Instructions for PreTrip BUS',
                'ordering': ('field_name',),
            },
        ),
        migrations.CreateModel(
            name='InstructionPreTripClassA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('field_name', models.CharField(default=None, help_text='Type/select field name underscore and without any space matched with db field', max_length=32, unique=True, verbose_name='Field Name')),
            ],
            options={
                'verbose_name': 'Instruction for PreTrip Class A',
                'verbose_name_plural': 'Instructions for PreTrip Class A',
                'ordering': ('field_name',),
            },
        ),
        migrations.CreateModel(
            name='InstructionPreTripClassB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('field_name', models.CharField(default=None, help_text='Type/select field name underscore and without any space matched with db field', max_length=32, unique=True, verbose_name='Field Name')),
            ],
            options={
                'verbose_name': 'Instruction for PreTrip Class B',
                'verbose_name_plural': 'Instructions for PreTrip Class B',
                'ordering': ('field_name',),
            },
        ),
        migrations.CreateModel(
            name='InstructionPreTripClassC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('field_name', models.CharField(default=None, help_text='Type/select field name underscore and without any space matched with db field', max_length=32, unique=True, verbose_name='Field Name')),
            ],
            options={
                'verbose_name': 'Instruction for PreTrip Class C',
                'verbose_name_plural': 'Instructions for PreTrip Class C',
                'ordering': ('field_name',),
            },
        ),
    ]
