# Generated by Django 2.2.19 on 2021-04-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0028_instructionswp_instructionvrt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btwbacking',
            old_name='size_of_situation',
            new_name='size_up_situation',
        ),
        migrations.RenameField(
            model_name='btwbackingbus',
            old_name='size_of_situation',
            new_name='size_up_situation',
        ),
        migrations.RenameField(
            model_name='btwbackingclassa',
            old_name='size_of_situation',
            new_name='size_up_situation',
        ),
        migrations.RenameField(
            model_name='btwbackingclassb',
            old_name='size_of_situation',
            new_name='size_up_situation',
        ),
        migrations.RenameField(
            model_name='btwbackingclassc',
            old_name='size_of_situation',
            new_name='size_up_situation',
        ),
        migrations.RenameField(
            model_name='btwbackingclassd',
            old_name='size_of_situation',
            new_name='size_up_situation',
        ),
        migrations.RenameField(
            model_name='pasbacking',
            old_name='size_of_situation',
            new_name='size_up_situation',
        ),
    ]
