# Generated by Django 2.2.19 on 2021-04-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0029_auto_20210404_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safedriveswp',
            options={'ordering': ('-created',), 'verbose_name': 'Safe Work Training(SWP)', 'verbose_name_plural': 'Safe Work Trainings(SWP)'},
        ),
        migrations.AddField(
            model_name='vehicleroadtest',
            name='qualified',
            field=models.BooleanField(default=False, verbose_name='Qualified'),
        ),
    ]
