# Generated by Django 2.2.19 on 2021-04-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0032_auto_20210408_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrtbacking',
            name='backs_slowly',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Backs Slowly'),
        ),
        migrations.AlterField(
            model_name='vrtbacking',
            name='checks_mirror',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Checks Mirror'),
        ),
        migrations.AlterField(
            model_name='vrtbacking',
            name='checks_rear',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Checks Rear'),
        ),
        migrations.AlterField(
            model_name='vrtbacking',
            name='communicates',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Communicates'),
        ),
        migrations.AlterField(
            model_name='vrtbacking',
            name='looks_out_window',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Looks Out Window'),
        ),
        migrations.AlterField(
            model_name='vrtbacking',
            name='steers_correctly',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Steers Correctly'),
        ),
        migrations.AlterField(
            model_name='vrtbacking',
            name='uses_other_aids',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Uses Other Aids'),
        ),
        migrations.AlterField(
            model_name='vrtcoupling',
            name='air_lines_or_light_cord',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Air Lines/Light Cord'),
        ),
        migrations.AlterField(
            model_name='vrtcoupling',
            name='equipment_alignment',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Equipment Alignment'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='alertness',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Alertness'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='area_knowledge',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Area Knowledge'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='following',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Following'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='intersections',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Intersections'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='left_turns',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Left Turns'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='passing',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Passing'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='right_of_turns',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Right Turns'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='right_of_way',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Right of Way'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='speed_control',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Speed Control'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='steering',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Steering'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='trafic_signals',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Traffic Signals'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='use_of_horn',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Use of Horn'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='use_of_lanes',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Use of Lanes'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='use_of_mirrors',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Use of Mirrors'),
        ),
        migrations.AlterField(
            model_name='vrtdrivinghabits',
            name='warning_signals',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Warning Signals'),
        ),
        migrations.AlterField(
            model_name='vrtengineoperations',
            name='lugging',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Lugging'),
        ),
        migrations.AlterField(
            model_name='vrtengineoperations',
            name='over_revving',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Over Revving'),
        ),
        migrations.AlterField(
            model_name='vrtparking',
            name='chocks_wheel',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Chocks Wheel'),
        ),
        migrations.AlterField(
            model_name='vrtparking',
            name='curbs_wheel',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Curbs Wheel'),
        ),
        migrations.AlterField(
            model_name='vrtparking',
            name='does_not_hit_dock',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Doesn’t Hit Dock'),
        ),
        migrations.AlterField(
            model_name='vrtparking',
            name='parking_brake_applied',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Parking Brake Applied'),
        ),
        migrations.AlterField(
            model_name='vrtparking',
            name='transmission_neutral',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Transmission Neutral'),
        ),
        migrations.AlterField(
            model_name='vrtposttrip',
            name='body_damage',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Body Damage'),
        ),
        migrations.AlterField(
            model_name='vrtposttrip',
            name='hub_heat',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Hub Heat'),
        ),
        migrations.AlterField(
            model_name='vrtposttrip',
            name='lights',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Lights'),
        ),
        migrations.AlterField(
            model_name='vrtposttrip',
            name='reflectors',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Reflectors'),
        ),
        migrations.AlterField(
            model_name='vrtposttrip',
            name='tires',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Tires'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='air_lines',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Air Lines'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='chassis_undercarriage',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Chassis Undercarriage'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='coupling_devices',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Coupling Devices'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='documents',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Documents'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='drain_air_tanks',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Drain Air Tanks'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='emergency_device',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Emergency Device'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='engine',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Engine'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='fluids',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Fluids'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='gauges',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Gauges'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='horn',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Horn'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='htr_air_dfr',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Htr/Air/Dfr'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='leaks_air_fluid',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Leaks/Air/Fluid'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='lights',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Lights'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='mirrors',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Mirrors'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='park_or_emer_brake',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Park/Emer Brake'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='pedals',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Pedals'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='reflectors',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Reflectors'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='steering',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Steering'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='switches',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Switches'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='tires',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Tires'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='wheels',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Wheels'),
        ),
        migrations.AlterField(
            model_name='vrtpretrip',
            name='wipers',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Wipers'),
        ),
        migrations.AlterField(
            model_name='vrtstartengine',
            name='clutch_depressed',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Clutch Depressed'),
        ),
        migrations.AlterField(
            model_name='vrtstartengine',
            name='park_brake_applied',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Park Brake Applied'),
        ),
        migrations.AlterField(
            model_name='vrtstartengine',
            name='reads_gauges',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Reads Gauges'),
        ),
        migrations.AlterField(
            model_name='vrtstartengine',
            name='starter_used_properly',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Starter Used Properly'),
        ),
        migrations.AlterField(
            model_name='vrtstartengine',
            name='transmission_in_neutral',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Transmission in Neutral'),
        ),
        migrations.AlterField(
            model_name='vrtuseclutch',
            name='disengages_completely',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Disengages Completely'),
        ),
        migrations.AlterField(
            model_name='vrtuseclutch',
            name='double_clutches_properly',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Double Clutches Properly'),
        ),
        migrations.AlterField(
            model_name='vrtuseclutch',
            name='engages_smoothly',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Engages Smoothly'),
        ),
        migrations.AlterField(
            model_name='vrtuseclutch',
            name='rides_clutch',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Rides Clutch'),
        ),
        migrations.AlterField(
            model_name='vrtuseofbrakes',
            name='engine_assist_brake',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Engine Assist Brake'),
        ),
        migrations.AlterField(
            model_name='vrtuseofbrakes',
            name='fans_brakes',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Fans Brakes'),
        ),
        migrations.AlterField(
            model_name='vrtuseofbrakes',
            name='foot_brake_only',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Foot Brake Only'),
        ),
        migrations.AlterField(
            model_name='vrtuseofbrakes',
            name='smoothly_applies',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Smoothly Applies'),
        ),
        migrations.AlterField(
            model_name='vrtuseofbrakes',
            name='stops_smoothly',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Stops Smoothly'),
        ),
        migrations.AlterField(
            model_name='vrtuseoftransmission',
            name='proper_sequence',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Proper Sequence'),
        ),
        migrations.AlterField(
            model_name='vrtuseoftransmission',
            name='starts_in_low_gear',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Starts in Low Gear'),
        ),
        migrations.AlterField(
            model_name='vrtuseoftransmission',
            name='timing_up',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Timing Up'),
        ),
    ]
