# Generated by Django 2.2.19 on 2021-04-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0033_auto_20210408_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrtparking',
            name='does_not_hit_dock',
        ),
        migrations.AddField(
            model_name='vrtparking',
            name='does_not_hit_curb',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=1, verbose_name='Doesn’t Hit Curb'),
        ),
    ]
