# Generated by Django 2.2.19 on 2021-04-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0034_auto_20210413_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrtuncoupling',
            name='verify_firm_to_ground',
            field=models.IntegerField(choices=[(0, 'N/A'), (1, 'Imp'), (2, 'Ok')], default=0, verbose_name='Verify Firm to Ground'),
        ),
        migrations.AlterField(
            model_name='vrtuseoftransmission',
            name='shifts_without_classing',
            field=models.IntegerField(default=1, verbose_name='Shifts without classing'),
        ),
    ]
