# Generated by Django 2.2.19 on 2021-04-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0035_auto_20210413_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttestinfo',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Location'),
        ),
    ]
