# Generated by Django 2.2.19 on 2021-04-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0036_studenttestinfo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentprobabilityvaluepretripbus',
            name='key',
            field=models.CharField(choices=[('inside_cab', 'Inside Cab'), ('coals', 'COALS'), ('engine_compartment', 'Engine Compartment'), ('vehicle_front', 'Vehicle Front'), ('both_sides_vehicle', 'Both Sides Vehicle'), ('vehicle_or_tractor_rear', 'Vehcile/Tractor Rear'), ('front_of_trailer_box', 'Front of Trailer Box - Header Board'), ('driver_side_trailer_or_box', 'Driver Side Trailer Or Box'), ('rear_trailer_and_box', 'Rear Trailer & Box'), ('passenger_side_trailer_or_box', 'Passenger Side Trailer Or Box'), ('dolly', 'Dolly'), ('post_trip', 'Post-Trip')], default=None, help_text='Type key name underscore and without any space', max_length=32, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='accidentprobabilityvaluepretripclassa',
            name='key',
            field=models.CharField(choices=[('inside_cab', 'Inside Cab'), ('coals', 'COALS'), ('engine_compartment', 'Engine Compartment'), ('vehicle_front', 'Vehicle Front'), ('both_sides_vehicle', 'Both Sides Vehicle'), ('vehicle_or_tractor_rear', 'Vehcile/Tractor Rear'), ('front_of_trailer_box', 'Front of Trailer Box - Header Board'), ('driver_side_trailer_or_box', 'Driver Side Trailer Or Box'), ('rear_trailer_and_box', 'Rear Trailer & Box'), ('passenger_side_trailer_or_box', 'Passenger Side Trailer Or Box'), ('dolly', 'Dolly'), ('post_trip', 'Post-Trip')], default=None, help_text='Type key name underscore and without any space', max_length=32, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='accidentprobabilityvaluepretripclassb',
            name='key',
            field=models.CharField(choices=[('inside_cab', 'Inside Cab'), ('coals', 'COALS'), ('engine_compartment', 'Engine Compartment'), ('vehicle_front', 'Vehicle Front'), ('both_sides_vehicle', 'Both Sides Vehicle'), ('vehicle_or_tractor_rear', 'Vehcile/Tractor Rear'), ('front_of_trailer_box', 'Front of Trailer Box - Header Board'), ('driver_side_trailer_or_box', 'Driver Side Trailer Or Box'), ('rear_trailer_and_box', 'Rear Trailer & Box'), ('passenger_side_trailer_or_box', 'Passenger Side Trailer Or Box'), ('dolly', 'Dolly'), ('post_trip', 'Post-Trip')], default=None, help_text='Type key name underscore and without any space', max_length=32, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='accidentprobabilityvaluepretripclassc',
            name='key',
            field=models.CharField(choices=[('inside_cab', 'Inside Cab'), ('coals', 'COALS'), ('engine_compartment', 'Engine Compartment'), ('vehicle_front', 'Vehicle Front'), ('both_sides_vehicle', 'Both Sides Vehicle'), ('vehicle_or_tractor_rear', 'Vehcile/Tractor Rear'), ('front_of_trailer_box', 'Front of Trailer Box - Header Board'), ('driver_side_trailer_or_box', 'Driver Side Trailer Or Box'), ('rear_trailer_and_box', 'Rear Trailer & Box'), ('passenger_side_trailer_or_box', 'Passenger Side Trailer Or Box'), ('dolly', 'Dolly'), ('post_trip', 'Post-Trip')], default=None, help_text='Type key name underscore and without any space', max_length=32, verbose_name='Key'),
        ),
    ]
