# Generated by Django 2.2.19 on 2021-04-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0037_auto_20210420_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accidentprobabilityvaluebtwbus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accidentprobabilityvaluebtwclassa',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accidentprobabilityvaluebtwclassb',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accidentprobabilityvaluebtwclassc',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accidentprobabilityvaluepretripbus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accidentprobabilityvaluepretripclassa',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accidentprobabilityvaluepretripclassb',
            name='name',
        ),
        migrations.RemoveField(
            model_name='accidentprobabilityvaluepretripclassc',
            name='name',
        ),
        migrations.RemoveField(
            model_name='injuryprobabilityvalueswp',
            name='name',
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluebtwbus',
            name='db_table',
            field=models.CharField(default=None, max_length=32, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluebtwclassa',
            name='db_table',
            field=models.CharField(default=None, max_length=32, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluebtwclassb',
            name='db_table',
            field=models.CharField(default=None, max_length=32, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluebtwclassc',
            name='db_table',
            field=models.CharField(default=None, max_length=32, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluepretripbus',
            name='db_table',
            field=models.CharField(default=None, max_length=32, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluepretripclassa',
            name='db_table',
            field=models.CharField(default=None, max_length=32, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluepretripclassb',
            name='db_table',
            field=models.CharField(default=None, max_length=32, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluepretripclassc',
            name='db_table',
            field=models.CharField(default=None, max_length=32, verbose_name='DB Table'),
        ),
    ]
