# Generated by Django 2.2.19 on 2021-04-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0038_auto_20210421_0624'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accidentprobabilityvaluebtwbus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='accidentprobabilityvaluebtwclassb',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='accidentprobabilityvaluebtwclassc',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='accidentprobabilityvaluepretripbus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='accidentprobabilityvaluepretripclassa',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='accidentprobabilityvaluepretripclassb',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='accidentprobabilityvaluepretripclassc',
            unique_together=set(),
        ),
    ]
