# Generated by Django 2.2.19 on 2021-04-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0039_auto_20210421_0639'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accidentprobabilityvaluebtwclassa',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='accidentprobabilityvaluebtwbus',
            constraint=models.UniqueConstraint(fields=('db_table', 'key', 'field_name'), name='unique_model_key_field_btw_bus'),
        ),
        migrations.AddConstraint(
            model_name='accidentprobabilityvaluebtwclassa',
            constraint=models.UniqueConstraint(fields=('db_table', 'key', 'field_name'), name='unique_model_key_field_btw_class_a'),
        ),
        migrations.AddConstraint(
            model_name='accidentprobabilityvaluebtwclassb',
            constraint=models.UniqueConstraint(fields=('db_table', 'key', 'field_name'), name='unique_model_key_field_btw_class_b'),
        ),
        migrations.AddConstraint(
            model_name='accidentprobabilityvaluebtwclassc',
            constraint=models.UniqueConstraint(fields=('db_table', 'key', 'field_name'), name='unique_model_key_field_btw_class_c'),
        ),
        migrations.AddConstraint(
            model_name='accidentprobabilityvaluepretripbus',
            constraint=models.UniqueConstraint(fields=('db_table', 'key', 'field_name'), name='unique_model_key_field_pretrip_bus'),
        ),
        migrations.AddConstraint(
            model_name='accidentprobabilityvaluepretripclassa',
            constraint=models.UniqueConstraint(fields=('db_table', 'key', 'field_name'), name='unique_model_key_field_pretrip_class_a'),
        ),
        migrations.AddConstraint(
            model_name='accidentprobabilityvaluepretripclassb',
            constraint=models.UniqueConstraint(fields=('db_table', 'key', 'field_name'), name='unique_model_key_field_pretrip_class_b'),
        ),
        migrations.AddConstraint(
            model_name='accidentprobabilityvaluepretripclassc',
            constraint=models.UniqueConstraint(fields=('db_table', 'key', 'field_name'), name='unique_model_key_field_pretrip_class_c'),
        ),
    ]
