# Generated by Django 2.2.19 on 2021-04-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0041_auto_20210421_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentprobabilityvaluebtwbus',
            name='model_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Model Name'),
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluebtwclassa',
            name='model_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Model Name'),
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluebtwclassb',
            name='model_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Model Name'),
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluebtwclassc',
            name='model_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Model Name'),
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluepretripbus',
            name='model_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Model Name'),
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluepretripclassa',
            name='model_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Model Name'),
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluepretripclassb',
            name='model_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Model Name'),
        ),
        migrations.AddField(
            model_name='accidentprobabilityvaluepretripclassc',
            name='model_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Model Name'),
        ),
    ]
