# Generated by Django 2.2.19 on 2021-05-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0045_auto_20210519_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentprobabilityvaluebtwbus',
            name='field_name',
            field=models.CharField(default=None, help_text='Type field name underscore and without any space matched with db field', max_length=250, verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='accidentprobabilityvaluebtwclassa',
            name='field_name',
            field=models.CharField(default=None, help_text='Type field name underscore and without any space matched with db field', max_length=250, verbose_name='Field Name'),
        ),
        migrations.AlterField(
            model_name='accidentprobabilityvaluebtwclassb',
            name='field_name',
            field=models.CharField(default=None, help_text='Type field name underscore and without any space matched with db field', max_length=250, verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='accidentprobabilityvaluebtwclassc',
            name='field_name',
            field=models.CharField(default=None, help_text='Type field name underscore and without any space matched with db field', max_length=250, verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='accidentprobabilityvaluepretripbus',
            name='field_name',
            field=models.CharField(default=None, help_text='Type field name underscore and without any space matched with db field', max_length=250, verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='accidentprobabilityvaluepretripclassa',
            name='field_name',
            field=models.CharField(default=None, help_text='Type field name underscore and without any space matched with db field', max_length=250, verbose_name='Field Name'),
        ),
        migrations.AlterField(
            model_name='accidentprobabilityvaluepretripclassc',
            name='field_name',
            field=models.CharField(default=None, help_text='Type field name underscore and without any space matched with db field', max_length=250, verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='injuryprobabilityvalueswp',
            name='field_name',
            field=models.CharField(default=None, help_text='Type field name underscore and without any space matched with db field', max_length=250, verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='injuryprobabilityvalueswp',
            name='key',
            field=models.CharField(choices=[('animal_bite', 'Animal Bite'), ('amputation', 'Amputation'), ('blunt_force_trauma', 'Blunt Force Trauma'), ('burn', 'Burn'), ('cut', 'Cut'), ('dehydration', 'Denydration'), ('fracture', 'Fracture'), ('frost_bite', 'Frost Bite'), ('heat_stress', 'Heat Stress'), ('sprain', 'Sprain'), ('spider_bite_sting', 'Spider Bite/Sting'), ('strain', 'Strain'), ('stress', 'Stess'), ('toxic_exposure', 'Toxic Exposure')], default=None, help_text='Type key name underscore and without any space', max_length=250, verbose_name='Key'),
        ),
    ]
