# Generated by Django 2.2.19 on 2021-06-01 20:37

from django.db import migrations, models
import safe_driver.models.common


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0046_auto_20210528_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swpkeysliftingandlowering',
            options={'ordering': ('-created',), 'verbose_name': 'SWP - Keys Lifting and Lowering'},
        ),
        migrations.AddField(
            model_name='studenttestnote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=safe_driver.models.common.student_test_note_image_path),
        ),
    ]
