# Generated by Django 2.2.19 on 2021-06-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0047_auto_20210602_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryprobabilityvalueswp',
            name='db_table',
            field=models.CharField(default=None, max_length=250, verbose_name='db_table'),
        ),
        migrations.AlterUniqueTogether(
            name='injuryprobabilityvalueswp',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='injuryprobabilityvalueswp',
            constraint=models.UniqueConstraint(fields=('db_table', 'key', 'field_name'), name='unique_value_fields_contraints'),
        ),
    ]
