# Generated by Django 2.2.19 on 2021-06-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0048_auto_20210602_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuryprobabilityvalueswp',
            name='db_table',
            field=models.CharField(default=None, max_length=250, verbose_name='Database Table'),
        ),
    ]
