# Generated by Django 2.2.19 on 2021-06-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0049_auto_20210604_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proditem',
            name='start_work',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Start Work'),
        ),
    ]
