# Generated by Django 2.2.19 on 2021-06-13 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safe_driver', '0050_auto_20210613_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttest',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_test_instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
