# Generated by Django 2.2.19 on 2021-06-15 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0051_studenttest_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreTripRampBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_lift', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Power Lift')),
                ('lift_door', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Lift Door')),
                ('buzzer', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Buzzer')),
                ('interlock', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Interlock')),
                ('identification', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Identification')),
                ('lights', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Lights')),
                ('fluid_and_air_leaks', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Fluid & Air Leaks')),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pre_trip_bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_ramp_bus', to='safe_driver.PreTripBus')),
            ],
            options={
                'verbose_name': 'Pre Trip Ramp Bus',
                'verbose_name_plural': 'Pre Trip Ramp Bus List',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PreTripInteriorOperationBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior_damage', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Interior Damage')),
                ('interior_cleanlines', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Interior Cleanliness')),
                ('first_aid_kit', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='First Aid Kit (If Applicable)')),
                ('emergency_door_buzzer', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Emergency Door Buzzer')),
                ('seat_belt_cutter', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Seat Belt Cutter')),
                ('seats', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Seats')),
                ('hand_rails', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Hand Rails')),
                ('stop_arm_control', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Stop Arm Control (if applicable)')),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pre_trip_bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_interior_operation_bus', to='safe_driver.PreTripBus')),
            ],
            options={
                'verbose_name': 'Pre Trip Interior Operations Bus',
                'verbose_name_plural': 'Pre Trip Interior Operations Bus List',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PreTripCargoAreaBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_cargo_door', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='All Cargo Door')),
                ('cargo_load_area', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Cargo, Load, Area')),
                ('all_securing_devices', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='All Securing Devices')),
                ('cargo_doors_hinges', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Card Doors Hinges')),
                ('door_locking_devices', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (0, 'N/A')], default=0, verbose_name='Door Locking Devices')),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pre_trip_bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pretrip_cargo_area_bus', to='safe_driver.PreTripBus')),
            ],
            options={
                'verbose_name': 'Pre Trip Cargo Area Bus',
                'verbose_name_plural': 'Pre Trip Cargo Area Bus List',
                'ordering': ('-created',),
            },
        ),
    ]
