# Generated by Django 2.2.19 on 2021-07-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0053_auto_20210708_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swpemployeesinterview',
            name='dehydration',
            field=models.BooleanField(default=True, verbose_name='Dehydration'),
        ),
        migrations.AlterField(
            model_name='swpemployeesinterview',
            name='demonstrate_power_zone',
            field=models.BooleanField(default=True, verbose_name='Demonstrate Power Zone'),
        ),
        migrations.AlterField(
            model_name='swpemployeesinterview',
            name='employee_understand_protocol',
            field=models.BooleanField(default=True, verbose_name='Employee Understand Protocol for Reporting Incidents Immediately'),
        ),
        migrations.AlterField(
            model_name='swpemployeesinterview',
            name='equipment_emergency_shut_offs',
            field=models.BooleanField(default=True, verbose_name='Equipment Emergency Shut Offs'),
        ),
        migrations.AlterField(
            model_name='swpemployeesinterview',
            name='evacuation_assembly',
            field=models.BooleanField(default=True, verbose_name='Evacuation Assembly'),
        ),
        migrations.AlterField(
            model_name='swpemployeesinterview',
            name='evacuation_notification',
            field=models.BooleanField(default=True, verbose_name='Evacuation Notification'),
        ),
        migrations.AlterField(
            model_name='swpemployeesinterview',
            name='evacuation_plan',
            field=models.BooleanField(default=True, verbose_name='Evacuation Plan'),
        ),
        migrations.AlterField(
            model_name='swpemployeesinterview',
            name='eye_wash',
            field=models.BooleanField(default=True, verbose_name='Eye Wash'),
        ),
        migrations.AlterField(
            model_name='swpemployeesinterview',
            name='nearest_exit',
            field=models.BooleanField(default=True, verbose_name='Nearest Exit'),
        ),
        migrations.AlterField(
            model_name='swpemployeesinterview',
            name='positive_attitude',
            field=models.BooleanField(default=True, verbose_name='Positive Attitude Towards Safety'),
        ),
    ]
