# Generated by Django 2.2.19 on 2021-07-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0055_auto_20210728_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btwturningclassb',
            old_name='gets_in_proper_time',
            new_name='gets_in_proper_lane',
        ),
    ]
