# Generated by Django 2.2.19 on 2021-08-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0057_btwbackingclassp_btwbrakesandstoppingsclassp_btwcabsafetyclassp_btwclassp_btwengineoperationclassp_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentProbabilityValuePreTripClassP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_table', models.CharField(default=None, max_length=250, verbose_name='DB Table')),
                ('model_name', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Model Name')),
                ('key', models.CharField(choices=[('inside_cab', 'Inside Cab'), ('coals', 'COALS'), ('engine_compartment', 'Engine Compartment'), ('vehicle_front', 'Vehicle Front'), ('both_sides_vehicle', 'Both Sides Vehicle'), ('vehicle_or_tractor_rear', 'Vehcile/Tractor Rear'), ('front_of_trailer_box', 'Front of Trailer Box - Header Board'), ('driver_side_trailer_or_box', 'Driver Side Trailer Or Box'), ('rear_trailer_and_box', 'Rear Trailer & Box'), ('passenger_side_trailer_or_box', 'Passenger Side Trailer Or Box'), ('dolly', 'Dolly'), ('post_trip', 'Post-Trip')], default=None, help_text='Type key name underscore and without any space', max_length=32, verbose_name='Key')),
                ('field_name', models.CharField(default=None, help_text='Type field name underscore and without any space matched with db field', max_length=250, verbose_name='Field')),
                ('value', models.DecimalField(decimal_places=2, default=None, help_text='Postive Value', max_digits=4, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Accident Probability Value PreTrip Class P',
                'verbose_name_plural': 'Accident Probability Value PreTrip Class P',
                'ordering': ('key', 'field_name'),
            },
        ),
        migrations.AlterModelOptions(
            name='pretripclassp',
            options={'ordering': ('-created',), 'verbose_name': 'Pre Trip Class P', 'verbose_name_plural': 'Pre Trips Class P'},
        ),
        migrations.AddConstraint(
            model_name='accidentprobabilityvaluepretripclassp',
            constraint=models.UniqueConstraint(fields=('db_table', 'key', 'field_name'), name='unique_model_key_field_pretrip_class_p'),
        ),
    ]
