# Generated by Django 2.2.19 on 2021-08-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0059_auto_20210815_0509'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionBTWClassP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('field_name', models.CharField(default=None, help_text='Type/select field name underscore and without any space matched with db field', max_length=250, unique=True, verbose_name='Field Name')),
            ],
            options={
                'verbose_name': 'Instruction for BTW Class P',
                'verbose_name_plural': 'Instructions for BTW Class P',
                'ordering': ('field_name',),
            },
        ),
        migrations.CreateModel(
            name='InstructionPreTripClassP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('field_name', models.CharField(default=None, help_text='Type/select field name underscore and without any space matched with db field', max_length=250, unique=True, verbose_name='Field Name')),
            ],
            options={
                'verbose_name': 'Instruction for PreTrip Class P',
                'verbose_name_plural': 'Instructions for PreTrip Class P',
                'ordering': ('field_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='instructionbtwbus',
            options={'ordering': ('field_name',), 'verbose_name': 'Instruction for BTW BUS', 'verbose_name_plural': 'Instructions for BTW BUS'},
        ),
        migrations.AlterModelOptions(
            name='instructionpretripbus',
            options={'ordering': ('field_name',), 'verbose_name': 'Instruction for PreTrip BUS', 'verbose_name_plural': 'Instructions for PreTrip Bus'},
        ),
    ]
