# Generated by Django 2.2.24 on 2021-10-14 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safe_driver', '0061_auto_20210825_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(instructor__isnull=False), fields=('name', 'instructor'), name='instructor_unique_company_name'),
        ),
    ]