# Generated by Django 2.2.24 on 2021-10-15 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0062_auto_20211014_0927'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='instructor_unique_company_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='instructor',
        ),
    ]
