# Generated by Django 2.2.24 on 2021-10-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0064_company_instructors'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionpretripclassp',
            name='db_table',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='DB Table'),
        ),
        migrations.AddConstraint(
            model_name='instructionpretripclassp',
            constraint=models.UniqueConstraint(condition=models.Q(db_table__isnull=False), fields=('db_table', 'field_name'), name='instruction_pretrip_class_p_db_field_unique'),
        ),
    ]
