# Generated by Django 2.2.24 on 2021-10-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0065_auto_20211019_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionpretripclassp',
            name='field_name',
            field=models.CharField(default=None, help_text='Type/select field name underscore and without any space matched with db field', max_length=250, verbose_name='Field Name'),
        ),
    ]
