# Generated by Django 2.2.24 on 2021-10-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0066_auto_20211019_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionbtwbus',
            name='db_table',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='instructionbtwclassa',
            name='db_table',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='instructionbtwclassb',
            name='db_table',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='instructionbtwclassc',
            name='db_table',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='instructionbtwclassp',
            name='db_table',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='instructionpretripbus',
            name='db_table',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='instructionpretripclassa',
            name='db_table',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='instructionpretripclassb',
            name='db_table',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='instructionpretripclassc',
            name='db_table',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='instructionswp',
            name='db_table',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='DB Table'),
        ),
        migrations.AddField(
            model_name='instructionvrt',
            name='db_table',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='DB Table'),
        ),
        migrations.AddConstraint(
            model_name='instructionbtwbus',
            constraint=models.UniqueConstraint(condition=models.Q(db_table__isnull=False), fields=('db_table', 'field_name'), name='instruction_btw_bus_db_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='instructionbtwclassa',
            constraint=models.UniqueConstraint(condition=models.Q(db_table__isnull=False), fields=('db_table', 'field_name'), name='instruction_btw_class_a_db_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='instructionbtwclassb',
            constraint=models.UniqueConstraint(condition=models.Q(db_table__isnull=False), fields=('db_table', 'field_name'), name='instruction_btw_class_b_db_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='instructionbtwclassc',
            constraint=models.UniqueConstraint(condition=models.Q(db_table__isnull=False), fields=('db_table', 'field_name'), name='instruction_btw_class_c_db_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='instructionbtwclassp',
            constraint=models.UniqueConstraint(condition=models.Q(db_table__isnull=False), fields=('db_table', 'field_name'), name='instruction_btw_class_p_db_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='instructionpretripbus',
            constraint=models.UniqueConstraint(condition=models.Q(db_table__isnull=False), fields=('db_table', 'field_name'), name='instruction_pretrip_bus_db_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='instructionpretripclassa',
            constraint=models.UniqueConstraint(condition=models.Q(db_table__isnull=False), fields=('db_table', 'field_name'), name='instruction_pretrip_class_a_db_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='instructionpretripclassb',
            constraint=models.UniqueConstraint(condition=models.Q(db_table__isnull=False), fields=('db_table', 'field_name'), name='instruction_pretrip_class_b_db_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='instructionpretripclassc',
            constraint=models.UniqueConstraint(condition=models.Q(db_table__isnull=False), fields=('db_table', 'field_name'), name='instruction_pretrip_class_c_db_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='instructionswp',
            constraint=models.UniqueConstraint(condition=models.Q(db_table__isnull=False), fields=('db_table', 'field_name'), name='instruction_swp_db_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='instructionvrt',
            constraint=models.UniqueConstraint(condition=models.Q(db_table__isnull=False), fields=('db_table', 'field_name'), name='instruction_pretrip_vrt_db_field_unique'),
        ),
    ]
