export const defenseQuiz = [
  {
    id: 0,
    question: 'How far ahead of your vehicle should your eyes be?',
    key: 'ahead_vehicle_eyes',
    type: 'checkbox',
    isTrue: null,
    option: [
      {id: 0, value: 0, label: '5 to 6 seconds', isChecked: false},
      {id: 1, value: 0, label: '20 seconds', isChecked: false},
      {id: 2, value: 0, label: '10 to 12 seconds', isChecked: false},
      {id: 3, value: 0, label: '6 to 12 seconds', isChecked: false},
    ],
  },
  {
    id: 1,
    question: 'How far ahead should you be aiming your vehicle?',
    key: 'ahead_aiming_vehicle',
    type: 'checkbox',
    isTrue: null,
    option: [
      {id: 0, value: 0, label: '5 seconds', isChecked: false},
      {id: 1, value: 0, label: '8 seconds', isChecked: false},
      {id: 2, value: 0, label: '10 seconds', isChecked: false},
      {id: 3, value: 0, label: '12 seconds', isChecked: false},
    ],
  },
  {
    id: 2,
    question:
      'You should avoid staring by moving your eyes every 2 seconds, your eyes should never be away from',
    key: 'avoid_staring_moving_eyes',
    type: 'boolean',
    value: false,
    option: [],
  },
  {
    id: 3,
    question: 'What are the 3 types of distractions?',
    key: 'types_of_distractions',
    type: 'checkbox',
    option: [
      {id: 0, value: 0, label: 'Visual', isChecked: false},
      {id: 1, value: 0, label: 'Physical', isChecked: false},
      {id: 2, value: 0, label: 'Manual', isChecked: false},
      {id: 3, value: 0, label: 'Cognitive', isChecked: false},
      {id: 4, value: 0, label: 'Verbal', isChecked: false},
    ],
  },
  {
    id: 4,
    question:
      'When approaching an intersection where the light is red, do you slow down enough and attempt not to stop.',
    key: 'intersection_slow_down',
    type: 'boolean',
    value: false,
    option: [],
  },
  {
    id: 5,
    question:
      'Prior to entering an intersection you check left, right and back to the left?',
    key: 'intersection_check_left',
    type: 'boolean',
    value: false,
    option: [],
  },
  {
    id: 6,
    question:
      'What are the priority items that you should identify in the front of your vehicle?',
    key: 'identify_priority_items',
    type: 'checkbox',
    option: [
      {id: 0, value: 0, label: 'Motorist', isChecked: false},
      {id: 1, value: 0, label: 'Pedestrians', isChecked: false},
      {id: 2, value: 0, label: 'Animals', isChecked: false},
      {id: 3, value: 0, label: 'Stale Green Light', isChecked: false},
      {id: 4, value: 0, label: 'Eyes ahead time', isChecked: false},
      {id: 5, value: 0, label: 'Parked cars', isChecked: false},
      {id: 6, value: 0, label: 'Intersections', isChecked: false},
      {id: 7, value: 0, label: 'Following time', isChecked: false},
    ],
  },
  {
    id: 7,
    question:
      'A stale green light is a light that you did not observe turn green and you do not know when it will change?',
    key: 'stale_green_light_change',
    type: 'boolean',
    value: false,
    option: [],
  },
  {
    id: 8,
    question:
      'A decision point is the point prior to the intersection, and if your vehicle reaches it without the light changing from green, you will proceed through the intersection without hesitation or acceleration?',
    key: 'decision_point_changing_green_light',
    type: 'boolean',
    value: false,
    option: [],
  },
  {
    id: 9,
    question:
      'Why should you count 3 seconds when starting up at an intersection?',
    key: 'intersection_count_three_seconds',
    type: 'checkbox',
    option: [
      {
        id: 0,
        value: 0,
        label: 'To allow cross traffic to clear',
        isChecked: false,
      },
      {id: 1, value: 0, label: 'To establish follow time', isChecked: false},
      {
        id: 2,
        value: 0,
        label: 'To establish a field of vision',
        isChecked: false,
      },
      {
        id: 3,
        value: 0,
        label: 'To allow the engine oil to rise',
        isChecked: false,
      },
    ],
  },
  {
    id: 10,
    question: 'What is the formula for Following Distance?',
    key: 'following_distance_formula',
    type: 'checkbox',
    option: [
      {
        id: 0,
        value: 0,
        label: "40' truck (under 40 MPH) = 4 sec's - (over 40MPH) =6 sec's",
        isChecked: false,
      },
      {
        id: 1,
        value: 0,
        label: "50' truck (under 40 MPH) = 4 sec's - (over 40MPH) =6 sec's",
        isChecked: false,
      },
      {
        id: 2,
        value: 0,
        label: "60' truck 6 sec's at all times.",
        isChecked: false,
      },
    ],
  },
  {
    id: 11,
    question: 'Proper following distance gives you?',
    key: 'following_distance_gives',
    type: 'checkbox',
    option: [
      {id: 0, value: 0, label: 'Better field of vision', isChecked: false},
      {id: 1, value: 0, label: 'Gives you time', isChecked: false},
      {id: 2, value: 0, label: 'It is not necessary', isChecked: false},
      {
        id: 3,
        value: 0,
        label: 'Can help avoid being hit in rear',
        isChecked: false,
      },
    ],
  },
  {
    id: 12,
    question:
      'When approaching a parked vehicle, you should look for signs of life?',
    key: 'parked_vehicle_life_signs',
    type: 'boolean',
    value: false,
    option: [],
  },
  {
    id: 13,
    question: 'How often should you check a mirror?',
    key: 'check_mirror',
    type: 'checkbox',
    option: [
      {id: 0, value: 0, label: "every 3 to 5 sec's", isChecked: false},
      {id: 1, value: 0, label: "every 8 to 10 sec's", isChecked: false},
      {id: 2, value: 0, label: "every 10 to 12 sec's", isChecked: false},
      {id: 3, value: 0, label: "every 5 to 8 sec's", isChecked: false},
    ],
  },
  {
    id: 14,
    question:
      'You should check your mirrors 3 times during a turn (beginning, middle and end).',
    key: 'check_mirror_during_turn',
    type: 'boolean',
    value: false,
    option: [],
  },
  {
    id: 15,
    question: 'What tools do you use to communicate?',
    key: 'communication_tools',
    type: 'checkbox',
    option: [
      {id: 0, value: 0, isChecked: false, label: 'Voice'},
      {id: 1, value: 0, isChecked: false, label: 'Signals'},
      {id: 2, value: 0, isChecked: false, label: 'Lights'},
      {id: 3, value: 0, isChecked: false, label: 'Hand signs'},
      {id: 4, value: 0, isChecked: false, label: 'Horn'},
    ],
  },
  {
    id: 16,
    question: 'You should signal a minimum of 100 feet in advance?',
    key: 'advance_signal_100_feet',
    type: 'boolean',
    value: false,
    option: [],
  },
  {
    id: 17,
    question: 'When backing, you should back in not out?',
    key: 'advance_signal',
    type: 'boolean',
    value: false,
    option: [],
  },
  {
    id: 18,
    question: 'What is your first choice when backing?',
    key: 'backing_first_choice',
    type: 'checkbox',
    option: [
      {
        id: 0,
        value: 0,
        isChecked: false,
        label: 'Back to the blind side/passenger side.',
      },
      {
        id: 1,
        value: 0,
        isChecked: false,
        label: 'Back to the sight side/driver side.',
      },
      {id: 2, value: 0, isChecked: false, label: 'Back straight back.'},
    ],
  },
  {
    id: 19,
    question: 'While backing, when in doubt - stop and get out and look?',
    key: 'look_while_backing_doubt',
    type: 'boolean',
    value: false,
    option: [],
  },
];
