# Generated by Django 2.2.19 on 2021-06-03 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('safe_driver', '0049_auto_20210604_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefensiveDriverKnowledgeQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahead_vehicle_eyes', models.BooleanField(default=False, verbose_name='How far ahead of your vehicle should your eyes be?')),
                ('ahead_aiming_vehicle', models.BooleanField(default=False, verbose_name='How far ahead should you be aiming your vehicle?')),
                ('avoid_staring_moving_eyes', models.BooleanField(default=False, verbose_name='You should avoid staring by moving your eyes every 2 seconds, your eyes should never be away from the front for more than 2 seconds?')),
                ('types_of_distractions', models.BooleanField(default=False, verbose_name='What are the 3 types of distractions?')),
                ('intersection_slow_down', models.BooleanField(default=False, verbose_name='When approaching an intersection where the light is red, do you slow down enough and attempt not to stop.')),
                ('intersection_check_left', models.BooleanField(default=False, verbose_name='Prior to entering an intersection you check left, right and back to the left?')),
                ('identify_priority_items', models.BooleanField(default=False, verbose_name='What are the priority items that you should identify in the front of your vehicle?')),
                ('stale_green_light_change', models.BooleanField(default=False, verbose_name='A stale green light is a light that you did not observe turn green and you do not know when it will change?')),
                ('decision_point_changing_green_light', models.BooleanField(default=False, verbose_name='A decision point is the point prior to the intersection, and if your vehicle reaches it without the light changing from green, you will proceed through the intersection without hesitation or acceleration?')),
                ('intersection_count_three_seconds', models.BooleanField(default=False, verbose_name='Why should you count 3 seconds when starting up at an intersection?')),
                ('following_distance_formula', models.BooleanField(default=False, verbose_name='What is the formula for Following Distance?')),
                ('following_distance_gives', models.BooleanField(default=False, verbose_name='Proper following distance gives you?')),
                ('parked_vehicle_life_signs', models.BooleanField(default=False, verbose_name='When approaching a parked vehicle, you should look for signs of life?')),
                ('check_mirror', models.BooleanField(default=False, verbose_name='How often should you check a mirror?')),
                ('check_mirror_during_turn', models.BooleanField(default=False, verbose_name='You should check your mirrors 3 times during a turn (beginning, middle and end).')),
                ('communication_tools', models.BooleanField(default=False, verbose_name='What tools do you use to communicate?')),
                ('advance_signal', models.BooleanField(default=False, verbose_name='You should signal a minimum of 100 feet in advance?')),
                ('advance_signal_100_feet', models.BooleanField(default=False, verbose_name='When backing, you should back in not out?')),
                ('backing_first_choice', models.BooleanField(default=False, verbose_name='What is your first choice when backing?')),
                ('look_while_backing_doubt', models.BooleanField(default=False, verbose_name='While backing, when in doubt - stop and get out and look?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safe_driver.StudentTest', verbose_name='Student Test')),
            ],
            options={
                'verbose_name': 'Defensive Driver Knowledge Quiz',
                'verbose_name_plural': 'Defensive Driver Knowledge Quiz',
            },
        ),
    ]
