# Generated by Django 2.2.19 on 2021-07-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0054_auto_20210710_2246'),
        ('truck_driving_school', '0002_auto_20210604_0300'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Training Location',
                'verbose_name_plural': 'Training Locations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DriverTrainigRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(default=1, verbose_name='Day')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('planned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Planned')),
                ('actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Actual')),
                ('initials', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Initials')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='truck_driving_school.TrainingLocation')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_training_record_test', to='safe_driver.StudentTest')),
            ],
            options={
                'verbose_name': 'Driver Training Record',
                'verbose_name_plural': 'Driver Training Records',
                'ordering': ('day', 'title'),
            },
        ),
    ]
