# Generated by Django 2.2.19 on 2021-07-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_driving_school', '0004_auto_20210726_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertrainigrecord',
            name='location',
            field=models.CharField(blank=True, choices=[('classroom', 'Classroom'), ('yard', 'Yard'), ('btw', 'BTW')], default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='TrainingLocation',
        ),
    ]
