# Generated by Django 2.2.19 on 2021-08-24 22:54

from django.db import migrations, models
import django.db.models.deletion
import truck_driving_school.models


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0061_auto_20210825_0442'),
        ('truck_driving_school', '0007_auto_20210824_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertrainigrecord',
            name='location',
            field=models.CharField(blank=True, choices=[('classroom', 'Classroom'), ('yard', 'Yard'), ('btw', 'BTW'), ('on_road', 'On Road')], default=None, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SchoolHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('completed_statisfactorily_on', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('driver_trainer_signature', models.ImageField(blank=True, default=None, null=True, upload_to=truck_driving_school.models.school_hours_signature_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_training_school_hours', to='safe_driver.StudentTest')),
            ],
            options={
                'verbose_name': 'Driver Training School Hours',
                'verbose_name_plural': 'Driver Training School Hours',
                'ordering': ('-created',),
            },
        ),
    ]
