# Generated by Django 2.2.19 on 2021-08-25 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_driving_school', '0011_traineebook_traineebookitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DQFRequirementItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('department', models.CharField(choices=[('hr', 'HR'), ('trainer', 'Trainer'), ('company', 'Company')], max_length=10, verbose_name='Department')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DQF Requirement Item',
                'verbose_name_plural': 'DQF Requirement Items',
                'ordering': ('-created',),
            },
        ),
        migrations.RemoveField(
            model_name='schoolcontroldqfrequirement',
            name='dqf_requirement',
        ),
        migrations.AlterField(
            model_name='traineebookitem',
            name='department',
            field=models.CharField(choices=[('hr', 'HR'), ('trainer', 'Trainer'), ('company', 'Company')], max_length=10, verbose_name='Department'),
        ),
        migrations.DeleteModel(
            name='DQFRequirement',
        ),
        migrations.AddField(
            model_name='schoolcontroldqfrequirement',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='truck_driving_school.DQFRequirementItem'),
            preserve_default=False,
        ),
    ]
