# Generated by Django 2.2.19 on 2021-09-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_driving_school', '0012_auto_20210826_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertrainigrecord',
            name='initials',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Initials'),
        ),
    ]
