# Generated by Django 2.2.24 on 2021-10-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_driving_school', '0013_auto_20210913_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivertrainigrecord',
            options={'ordering': ('day', 'position'), 'verbose_name': 'Driver Training Record', 'verbose_name_plural': 'Driver Training Records'},
        ),
        migrations.AddField(
            model_name='drivertrainigrecord',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
