# Generated by Django 2.2.24 on 2021-10-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_driving_school', '0014_auto_20211004_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dqfrequirementitem',
            options={'ordering': ('position',), 'verbose_name': 'DQF Requirement Item', 'verbose_name_plural': 'DQF Requirement Items'},
        ),
        migrations.AlterModelOptions(
            name='schoolcontroldqfrequirement',
            options={'ordering': ('item__position',), 'verbose_name': 'School Control DQF Requirement', 'verbose_name_plural': 'School Control DQF Requirements'},
        ),
        migrations.AlterModelOptions(
            name='traineebook',
            options={'ordering': ('item__position',), 'verbose_name': 'Trainee Book', 'verbose_name_plural': 'Trainee Books'},
        ),
        migrations.AlterModelOptions(
            name='traineebookitem',
            options={'ordering': ('position',), 'verbose_name': 'Trainee Book Item', 'verbose_name_plural': 'Trainee Book Items'},
        ),
        migrations.AddField(
            model_name='dqfrequirementitem',
            name='position',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='traineebookitem',
            name='position',
            field=models.BooleanField(default=0),
        ),
    ]
