# Generated by Django 2.2.24 on 2021-10-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_driving_school', '0015_auto_20211007_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqfrequirementitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='traineebookitem',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
