# Generated by Django 2.2.24 on 2021-11-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safe_driver', '0068_auto_20211020_2046'),
        ('truck_driving_school', '0018_trainingrecordcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainginRecordDayComment',
            new_name='TrainingRecordDayComment',
        ),
    ]
